version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rafael
      MYSQL_DATABASE: go_boilerplate
      MYSQL_USER: rafael
      MYSQL_PASSWORD: rafael
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db
